version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped   # Auto restart on crash

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery:
    build: .
    container_name: celery_worker
    command: celery -A notification_system worker --loglevel=info --pool=solo # --pool=solo is more stable on Render free tier.
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data: